name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Define image tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/speedtest-for-influxdb-and-grafana:${{env.IMAGE_TAG}}
    - name: Tag Docker image as latest
      run: docker tag ${{secrets.DOCKER_USER}}/speedtest-for-influxdb-and-grafana:${{env.IMAGE_TAG}} ${{secrets.DOCKER_USER}}/speedtest-for-influxdb-and-grafana:latest
    - name: Publish the Docker image
      run: docker push --all-tags ${{secrets.DOCKER_USER}}/speedtest-for-influxdb-and-grafana
